name: Flywheel SSH Deploy

#on:
#  push:
#    branches: [main]
#or
#on: [push]

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PORT: 22 -o PubkeyAcceptedKeyTypes=+ssh-rsa
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TARGET: /www/wp-content/themes/
          ARGS: -rltgoDzvO
          EXCLUDE: "/.git, /.github, /README.md, /.DS_Store, /node_modules/"
